### ISSUE TITLE
CEO can take over the roles of CFO / COO

### ISSUE THREAD

**Issue by palanisn** [axiomzen/cryptokitties-bounty#7]
### Description
CEO can take over the roles of CFO / COO

### Scenario
The CEO is the only role that has permissions to change the values of the CFO / COO. But there is no check in place to ensure that the CEO doesn't take over all 'C' roles.

### Impact
CEO monopolises the control of the 'C' roles and the contract.

### Reproduction
See above.

### Fix
Add require statements to ensure that _newCFO / _newCOO values are not equal to ceoAddress.

**Comment by dete** [comment]
Thanks for reporting, @palanisn!

This is by design. If an unauthorized party gets control of the CEO address, they can easily create a new address under their control to set as CFO and COO. Ensuring these are distinct doesn't result in any added security.

Keep looking! We appreciate your analysis.
